#version: '3.8'

services:
  rms-fe:
    image: thanhkt/rms-fe:latest
    container_name: rms-fe
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BACKEND_URL=https://dev-be-competition.steam-sharing.online
      - NEXT_PUBLIC_API_URL=https://dev-be-competition.steam-sharing.online/api
      - NEXT_PUBLIC_WS_URL=wss://dev-be-competition.steam-sharing.online
      - NEXT_PUBLIC_APP_ENV=production
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    depends_on:
      - rms-be
    restart: unless-stopped

  rms-be:
    image: thanhkt/rms-be:latest
    container_name: rms-be
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - PORT=${BACKEND_PORT:-5000}
      - FRONTEND_URL=https://dev-competition.steam-sharing.online
    ports:
      - "${BACKEND_PORT:-5000}:5000"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: rms-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - rms-be
      - rms-fe
    restart: unless-stopped