// Re-export types from Prisma client to simplify imports
export { 
  UserRole,
  StageType,
  StageStatus,
  CardType,
  MatchState,
  DisplayState,
  AllianceColor,
  MatchRoundType,
  TimerType,
  MatchErrorType,
  ElementType,
  User,
  Tournament,
  Stage,
  Match,
  Alliance,
  Team,
  TeamAlliance,
  MatchReferee,
  Field,
  FieldDisplay,
  TeamStats,
  MatchType,
  ScoreConfig,
  ScoreElement,
  BonusCondition,
  PenaltyCondition,
  MatchScore,
  Gender,

} from '../../generated/prisma';