export { CreateScoreConfigDto } from './create-score-config.dto';
export { CreateScoreElementDto } from './create-score-element.dto';
export { CreateBonusConditionDto } from './create-bonus-condition.dto';
export { CreatePenaltyConditionDto } from './create-penalty-condition.dto';
export { CreateScoreSectionDto } from './create-score-section.dto';
export { SubmitScoreDto } from './submit-score.dto';
export * from './update-score-element.dto';
export * from './update-bonus-condition.dto';
export * from './update-penalty-condition.dto';
export * from './update-score-section.dto';
